### ANN

In [1]:
import pandas as pd;
from sklearn.model_selection import train_test_split;
from sklearn.preprocessing import OneHotEncoder,LabelEncoder;
import pickle;

In [2]:
df=pd.read_csv('Churn_Modelling.csv');
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
df=df.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [4]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
df['Geography'].unique()

<ArrowStringArray>
['France', 'Spain', 'Germany']
Length: 3, dtype: str

In [6]:
le_gender=LabelEncoder()

In [7]:
df['Gender']=le_gender.fit_transform(df['Gender'])

In [8]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [9]:
df['Gender'].unique()

array([0, 1])

In [10]:
le_gender.classes_

array(['Female', 'Male'], dtype=object)

In [11]:
ohe_geography=OneHotEncoder();
gen_encoded=ohe_geography.fit_transform(df[['Geography']])

In [12]:
import numpy as np;

In [13]:
ohe_geography.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [14]:
gen_encoded.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [15]:
pd.DataFrame(gen_encoded.toarray(),columns=ohe_geography.get_feature_names_out(['Geography']))

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [16]:
new_df = pd.concat([df,pd.DataFrame(gen_encoded.toarray(),columns=ohe_geography.get_feature_names_out(['Geography']))],axis=1)

In [17]:
new_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,France,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,France,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [18]:
new_df=new_df.drop(['Geography'],axis=1)

In [19]:
new_df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [20]:
pickle.dump(le_gender,open('label_encoder_gender.pkl','wb'));

In [21]:
pickle.dump(ohe_geography,open('label_encoder_geography.pkl','wb'));

In [22]:
x=new_df.drop('Exited',axis=1)
y=new_df['Exited']

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [24]:
from sklearn.preprocessing import StandardScaler;

In [25]:
scalar=StandardScaler();

In [26]:
x_train=scalar.fit_transform(x_train)
x_test=scalar.transform(x_test)

In [27]:
pickle.dump(scalar,open('scalar.pkl','wb'))

In [ ]:
import tensorflow as tf;
from tensorflow.keras.models import Sequential;
from tensorflow.keras.layers import Dense;
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard;

In [29]:
x_train.shape[1]

12

In [ ]:
### Build ANN Model

model=Sequential(
    [
        Dense(64,activation='relu',input_shape=(x_train.shape[1],)),### HL1 connect with input
        Dense(32,activation='relu'), ## HL2
        Dense(1,activation='sigmoid') ## Output Layer
    ]
)

In [31]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [32]:
opt=tf.keras.optimizers.Adam(learning_rate=0.01)

In [33]:
## Compile the model
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

In [34]:
import datetime;

In [35]:
### set up tensor board
log_dir="logs/fit/"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [36]:
#### set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [ ]:
#### Training the Model
history=model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=100
                  ,callbacks=[tensorflow_callback,early_stopping_callback]
                  )

In [ ]:
model.save('model.h5')

In [63]:
#### Load Tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [64]:
%reload_ext tensorboard

In [ ]:
!del /q /f /s %TMP%\.tensorboard-info\*

In [68]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 11844), started 0:00:10 ago. (Use '!kill 11844' to kill it.)