In [1]:
import tensorflow as tf;
from tensorflow.keras.models import load_model;
import pickle
import pandas as pd;
import numpy as np;

In [4]:
model=load_model('model.h5');
with open('label_encoder_gender.pkl','rb') as file:
    oneHot_encoder_gen=pickle.load(file)

In [5]:
with open('label_encoder_geography.pkl','rb') as file:
    label_encoder_geo=pickle.load(file)

In [6]:
with open('scalar.pkl','rb') as file:
    scalar=pickle.load(file)

In [7]:
input_data={
    'CreditScore': 600,
    'Geography' : 'France',
    'Gender' : 'Male',
    'Age' : 40,
    'Tenure' : 3,
    'Balance' : 60000,
    'NumOfProducts' : 2,
    'HasCrCard' : 1,
    'IsActiveMember' : 1,
    'EstimatedSalary' : 50000
}

In [8]:
input_data['Geography']

'France'

In [ ]:
geo_encoded=label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=label_encoder_geo.get_feature_names_out(['Geography']))

In [13]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [15]:
input_data=pd.DataFrame([input_data])

In [16]:
input_data

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [17]:
input_data['Gender']=oneHot_encoder_gen.transform(input_data['Gender'])

In [18]:
input_data

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France       1  ...          1               1            50000

[1 rows x 10 columns]

In [28]:
input_data_df=pd.concat([input_data,geo_encoded_df],axis=1)

In [29]:
input_data_df.drop(columns=['Geography'],inplace=True)

In [30]:
input_data_df

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [31]:
input_data_df_scaled=scalar.transform(input_data_df)

In [32]:
input_data_df_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [39]:
predict=model.predict(input_data_df_scaled)

1/1 [==============================] - 0s 169ms/step

In [38]:
label_encoder_geo.categories_[0]

array(['France', 'Germany', 'Spain'], dtype=object)

In [43]:
predict[0][0]

0.05957867